//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tomato.TomatoMusic.RpcPackets.IAudioControllerHandler
{
	public sealed class Void_20NotifyControllerReady_28_29
	{
	}

	public sealed class Void_20NotifyMediaOpened_28_29
	{
	}

	public sealed class Void_20NotifyControllerStateChanged_28Windows_Media_Playback_MediaPlayerState_29
	{
		public Windows.Media.Playback.MediaPlayerState Arg0;
	}

	public sealed class Void_20NotifyCurrentTrackChanged_28Tomato_TomatoMusic_Primitives_TrackInfo_29
	{
		public Tomato.TomatoMusic.Primitives.TrackInfo Arg0;
	}

	public sealed class Void_20NotifyDuration_28System_Nullable_601_5BSystem_TimeSpan_5D_29
	{
		public System.Nullable<System.TimeSpan> Arg0;
	}

	public sealed class Void_20NotifyPosition_28System_TimeSpan_29
	{
		public System.TimeSpan Arg0;
	}

	public sealed class Void_20NotifySeekCompleted_28_29
	{
	}

	public sealed class Void_20NotifyPlaylist_28System_Collections_Generic_IList_601_5BTomato_TomatoMusic_Primitives_TrackInfo_5D_29
	{
		public System.Collections.Generic.IList<Tomato.TomatoMusic.Primitives.TrackInfo> Arg0;
	}

}

