//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tomato.TomatoMusic.RpcPackets.IAudioController
{
	public sealed class Void_20SetupHandler_28_29
	{
	}

	public sealed class Void_20Play_28_29
	{
	}

	public sealed class Void_20Pause_28_29
	{
	}

	public sealed class Void_20SetPlaylist_28System_Collections_Generic_IList_601_5BTomato_TomatoMusic_Primitives_TrackInfo_5D_29
	{
		public System.Collections.Generic.IList<Tomato.TomatoMusic.Primitives.TrackInfo> Arg0;
	}

	public sealed class Void_20SetCurrentTrack_28Tomato_TomatoMusic_Primitives_TrackInfo_29
	{
		public Tomato.TomatoMusic.Primitives.TrackInfo Arg0;
	}

	public sealed class Void_20MoveNext_28_29
	{
	}

	public sealed class Void_20MovePrevious_28_29
	{
	}

	public sealed class Void_20SetPlayMode_28System_Guid_29
	{
		public System.Guid Arg0;
	}

	public sealed class Void_20AskPosition_28_29
	{
	}

	public sealed class Void_20SetPosition_28System_TimeSpan_29
	{
		public System.TimeSpan Arg0;
	}

	public sealed class Void_20SetVolume_28Double_29
	{
		public System.Double Arg0;
	}

}

