//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Tomato.TomatoMusic.RpcPackets.IAudioController;

namespace Tomato.TomatoMusic.RpcCalledProxies
{
	sealed class IAudioControllerRpcCalledProxy : global::Tomato.Rpc.Core.IPacketReceiver
	{
		private readonly Tomato.TomatoMusic.Core.IAudioController _impl;
		private readonly Dictionary<Type, Action<object>> _packetMethodMap;

		public IAudioControllerRpcCalledProxy(Tomato.TomatoMusic.Core.IAudioController impl)
		{
			_impl = impl;
			_packetMethodMap = new Dictionary<Type, Action<object>>
			{
				{ typeof(Void_20SetupHandler_28_29), ProcessVoid_20SetupHandler_28_29 },
				{ typeof(Void_20Play_28_29), ProcessVoid_20Play_28_29 },
				{ typeof(Void_20Pause_28_29), ProcessVoid_20Pause_28_29 },
				{ typeof(Void_20SetPlaylist_28System_Collections_Generic_IList_601_5BTomato_TomatoMusic_Primitives_TrackInfo_5D_29), ProcessVoid_20SetPlaylist_28System_Collections_Generic_IList_601_5BTomato_TomatoMusic_Primitives_TrackInfo_5D_29 },
				{ typeof(Void_20SetCurrentTrack_28Tomato_TomatoMusic_Primitives_TrackInfo_29), ProcessVoid_20SetCurrentTrack_28Tomato_TomatoMusic_Primitives_TrackInfo_29 },
				{ typeof(Void_20MoveNext_28_29), ProcessVoid_20MoveNext_28_29 },
				{ typeof(Void_20MovePrevious_28_29), ProcessVoid_20MovePrevious_28_29 },
				{ typeof(Void_20SetPlayMode_28System_Guid_29), ProcessVoid_20SetPlayMode_28System_Guid_29 },
				{ typeof(Void_20AskPosition_28_29), ProcessVoid_20AskPosition_28_29 },
				{ typeof(Void_20SetPosition_28System_TimeSpan_29), ProcessVoid_20SetPosition_28System_TimeSpan_29 },
				{ typeof(Void_20SetVolume_28Double_29), ProcessVoid_20SetVolume_28Double_29 },
				{ typeof(Void_20AskPlaylist_28_29), ProcessVoid_20AskPlaylist_28_29 },
				{ typeof(Void_20AskCurrentTrack_28_29), ProcessVoid_20AskCurrentTrack_28_29 },
				{ typeof(Void_20AskCurrentState_28_29), ProcessVoid_20AskCurrentState_28_29 },
			};
		}

		public void OnReceive(object packet)
		{
			Action<object> processor;
			if(_packetMethodMap.TryGetValue(packet.GetType(), out processor))
				processor(packet);
		}

		void ProcessVoid_20SetupHandler_28_29(object packetObj)
		{
			var packet = (Void_20SetupHandler_28_29)packetObj;
			_impl.SetupHandler();
		}

		void ProcessVoid_20Play_28_29(object packetObj)
		{
			var packet = (Void_20Play_28_29)packetObj;
			_impl.Play();
		}

		void ProcessVoid_20Pause_28_29(object packetObj)
		{
			var packet = (Void_20Pause_28_29)packetObj;
			_impl.Pause();
		}

		void ProcessVoid_20SetPlaylist_28System_Collections_Generic_IList_601_5BTomato_TomatoMusic_Primitives_TrackInfo_5D_29(object packetObj)
		{
			var packet = (Void_20SetPlaylist_28System_Collections_Generic_IList_601_5BTomato_TomatoMusic_Primitives_TrackInfo_5D_29)packetObj;
			_impl.SetPlaylist(packet.Arg0);
		}

		void ProcessVoid_20SetCurrentTrack_28Tomato_TomatoMusic_Primitives_TrackInfo_29(object packetObj)
		{
			var packet = (Void_20SetCurrentTrack_28Tomato_TomatoMusic_Primitives_TrackInfo_29)packetObj;
			_impl.SetCurrentTrack(packet.Arg0);
		}

		void ProcessVoid_20MoveNext_28_29(object packetObj)
		{
			var packet = (Void_20MoveNext_28_29)packetObj;
			_impl.MoveNext();
		}

		void ProcessVoid_20MovePrevious_28_29(object packetObj)
		{
			var packet = (Void_20MovePrevious_28_29)packetObj;
			_impl.MovePrevious();
		}

		void ProcessVoid_20SetPlayMode_28System_Guid_29(object packetObj)
		{
			var packet = (Void_20SetPlayMode_28System_Guid_29)packetObj;
			_impl.SetPlayMode(packet.Arg0);
		}

		void ProcessVoid_20AskPosition_28_29(object packetObj)
		{
			var packet = (Void_20AskPosition_28_29)packetObj;
			_impl.AskPosition();
		}

		void ProcessVoid_20SetPosition_28System_TimeSpan_29(object packetObj)
		{
			var packet = (Void_20SetPosition_28System_TimeSpan_29)packetObj;
			_impl.SetPosition(packet.Arg0);
		}

		void ProcessVoid_20SetVolume_28Double_29(object packetObj)
		{
			var packet = (Void_20SetVolume_28Double_29)packetObj;
			_impl.SetVolume(packet.Arg0);
		}

		void ProcessVoid_20AskPlaylist_28_29(object packetObj)
		{
			var packet = (Void_20AskPlaylist_28_29)packetObj;
			_impl.AskPlaylist();
		}

		void ProcessVoid_20AskCurrentTrack_28_29(object packetObj)
		{
			var packet = (Void_20AskCurrentTrack_28_29)packetObj;
			_impl.AskCurrentTrack();
		}

		void ProcessVoid_20AskCurrentState_28_29(object packetObj)
		{
			var packet = (Void_20AskCurrentState_28_29)packetObj;
			_impl.AskCurrentState();
		}

	}
}

