//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Tomato.TomatoMusic.RpcPackets.IAudioControllerHandler;

namespace Tomato.TomatoMusic.RpcCalledProxies
{
	sealed class IAudioControllerHandlerRpcCalledProxy : global::Tomato.Rpc.Core.IPacketReceiver
	{
		private readonly Tomato.TomatoMusic.Core.IAudioControllerHandler _impl;
		private readonly Dictionary<Type, Action<object>> _packetMethodMap;

		public IAudioControllerHandlerRpcCalledProxy(Tomato.TomatoMusic.Core.IAudioControllerHandler impl)
		{
			_impl = impl;
			_packetMethodMap = new Dictionary<Type, Action<object>>
			{
				{ typeof(Void_20NotifyControllerReady_28_29), ProcessVoid_20NotifyControllerReady_28_29 },
				{ typeof(Void_20NotifyMediaOpened_28_29), ProcessVoid_20NotifyMediaOpened_28_29 },
				{ typeof(Void_20NotifyControllerStateChanged_28Windows_Media_Playback_MediaPlayerState_29), ProcessVoid_20NotifyControllerStateChanged_28Windows_Media_Playback_MediaPlayerState_29 },
				{ typeof(Void_20NotifyCurrentTrackChanged_28Tomato_TomatoMusic_Primitives_TrackInfo_29), ProcessVoid_20NotifyCurrentTrackChanged_28Tomato_TomatoMusic_Primitives_TrackInfo_29 },
				{ typeof(Void_20NotifyDuration_28System_Nullable_601_5BSystem_TimeSpan_5D_29), ProcessVoid_20NotifyDuration_28System_Nullable_601_5BSystem_TimeSpan_5D_29 },
				{ typeof(Void_20NotifyPosition_28System_TimeSpan_29), ProcessVoid_20NotifyPosition_28System_TimeSpan_29 },
				{ typeof(Void_20NotifySeekCompleted_28_29), ProcessVoid_20NotifySeekCompleted_28_29 },
				{ typeof(Void_20NotifyPlaylist_28System_Collections_Generic_IList_601_5BTomato_TomatoMusic_Primitives_TrackInfo_5D_29), ProcessVoid_20NotifyPlaylist_28System_Collections_Generic_IList_601_5BTomato_TomatoMusic_Primitives_TrackInfo_5D_29 },
			};
		}

		public void OnReceive(object packet)
		{
			Action<object> processor;
			if(_packetMethodMap.TryGetValue(packet.GetType(), out processor))
				processor(packet);
		}

		void ProcessVoid_20NotifyControllerReady_28_29(object packetObj)
		{
			var packet = (Void_20NotifyControllerReady_28_29)packetObj;
			_impl.NotifyControllerReady();
		}

		void ProcessVoid_20NotifyMediaOpened_28_29(object packetObj)
		{
			var packet = (Void_20NotifyMediaOpened_28_29)packetObj;
			_impl.NotifyMediaOpened();
		}

		void ProcessVoid_20NotifyControllerStateChanged_28Windows_Media_Playback_MediaPlayerState_29(object packetObj)
		{
			var packet = (Void_20NotifyControllerStateChanged_28Windows_Media_Playback_MediaPlayerState_29)packetObj;
			_impl.NotifyControllerStateChanged(packet.Arg0);
		}

		void ProcessVoid_20NotifyCurrentTrackChanged_28Tomato_TomatoMusic_Primitives_TrackInfo_29(object packetObj)
		{
			var packet = (Void_20NotifyCurrentTrackChanged_28Tomato_TomatoMusic_Primitives_TrackInfo_29)packetObj;
			_impl.NotifyCurrentTrackChanged(packet.Arg0);
		}

		void ProcessVoid_20NotifyDuration_28System_Nullable_601_5BSystem_TimeSpan_5D_29(object packetObj)
		{
			var packet = (Void_20NotifyDuration_28System_Nullable_601_5BSystem_TimeSpan_5D_29)packetObj;
			_impl.NotifyDuration(packet.Arg0);
		}

		void ProcessVoid_20NotifyPosition_28System_TimeSpan_29(object packetObj)
		{
			var packet = (Void_20NotifyPosition_28System_TimeSpan_29)packetObj;
			_impl.NotifyPosition(packet.Arg0);
		}

		void ProcessVoid_20NotifySeekCompleted_28_29(object packetObj)
		{
			var packet = (Void_20NotifySeekCompleted_28_29)packetObj;
			_impl.NotifySeekCompleted();
		}

		void ProcessVoid_20NotifyPlaylist_28System_Collections_Generic_IList_601_5BTomato_TomatoMusic_Primitives_TrackInfo_5D_29(object packetObj)
		{
			var packet = (Void_20NotifyPlaylist_28System_Collections_Generic_IList_601_5BTomato_TomatoMusic_Primitives_TrackInfo_5D_29)packetObj;
			_impl.NotifyPlaylist(packet.Arg0);
		}

	}
}

